### ISSUE TITLE
Email settings are ignored when chart upgraded/deployed

### ISSUE THREAD

**Issue by artichoked1** [halkeye-helm-charts/synapse#33]
When you place anything under the `homeserver.email`, the configuration will get ignored and removed from the values file. For example:

If you add this to the values.yaml:
```
homeserver:
  email:
    smtp_host: mail.server
    smtp_port: 587
    smtp_user: "exampleusername"
    smtp_pass: "examplepassword"
    force_tls: true
    require_transport_security: true
    enable_tls: false
    notif_from: "Your Friendly %(app)s homeserver <noreply@example.com>"
    app_name: my_branded_matrix_server
    enable_notifs: true
    notif_for_new_users: false
    client_base_url: "http://localhost/riot"
    validation_token_lifetime: 15m
    invite_client_location: https://app.element.io
```

the entire `email` configuration section gets removed and and doesnt end up in the `homeserver.yaml` file.
